name: AspAuth Build and Push
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install .NET 10
        # If the image doesn't have 10.0 yet, we install it manually
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install GitVersion
        run: |
          dotnet tool install --global GitVersion.Tool
          # Force the path update for the current session
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Determine Version
        id: gitversion
        run: |
          # Use the full path just to be safe
          $HOME/.dotnet/tools/dotnet-gitversion /output buildserver
          
          VERSION=$($HOME/.dotnet/tools/dotnet-gitversion /showvariable FullSemVer)
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Log in to Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login dev.logout.work -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
      - name: Build
        run: docker build -f AspAuth.Local/Containerfile -t dev.logout.work/empire/aspauth:${{ env.PACKAGE_VERSION }} -t dev.logout.work/empire/aspauth:latest .
      - name: Push
        run: |
          docker push dev.logout.work/empire/aspauth:${{ env.PACKAGE_VERSION }}
          docker push dev.logout.work/empire/aspauth:latest