name: AspAuth Build and Push
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: GitTools/actions/gitversion/execute@v0.11.0
      - name: Show version
        run: echo "Version: ${{ env.GitVersion_SemVer }}"
      - name: Log in to Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login dev.logout.work -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
      - name: Build
        run: docker build -f AspAuth.Local/Containerfile -t dev.logout.work/empire/aspauth:${{ env.GitVersion_SemVer }} -t dev.logout.work/empire/aspauth:latest .
      - name: Push
        run: |
          docker push dev.logout.work/empire/aspauth:${{ env.GitVersion_SemVer }}
          docker push dev.logout.work/empire/aspauth:latest