// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5057/' | (string & {});
};

export type UserDto = {
    id: string;
    userName: string;
    email: string;
    fullName?: null | string;
};

export type GetApiUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Users';
};

export type GetApiUsersResponses = {
    /**
     * OK
     */
    200: Array<UserDto>;
};

export type GetApiUsersResponse = GetApiUsersResponses[keyof GetApiUsersResponses];
