// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5057/' | (string & {});
};

export type UserDto = {
    id: string;
    userName: string;
    email: string;
    fullName?: null | string;
};

export enum UserRoles {
    ADMIN = 'Admin'
}

export type GetApiUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Users';
};

export type GetApiUsersResponses = {
    /**
     * OK
     */
    200: Array<UserDto>;
};

export type GetApiUsersResponse = GetApiUsersResponses[keyof GetApiUsersResponses];

export type GetApiUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Users/{id}';
};

export type GetApiUsersByIdResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetApiUsersByIdResponse = GetApiUsersByIdResponses[keyof GetApiUsersByIdResponses];

export type GetApiUsersByIdRolesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Users/{id}/roles';
};

export type GetApiUsersByIdRolesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetApiUsersByIdRolesResponse = GetApiUsersByIdRolesResponses[keyof GetApiUsersByIdRolesResponses];

export type PutApiUsersByIdRolesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        role?: UserRoles;
    };
    url: '/api/Users/{id}/roles';
};

export type PutApiUsersByIdRolesResponses = {
    /**
     * OK
     */
    200: unknown;
};
