// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zAccessTokenType = z.int();

export type AccessTokenTypeZodType = z.infer<typeof zAccessTokenType>;

export const zClientClaim = z.object({
    type: z.optional(z.string()),
    value: z.optional(z.string()),
    valueType: z.optional(z.string())
});

export type ClientClaimZodType = z.infer<typeof zClientClaim>;

export const zClientUrlPatch = z.object({
    url: z.string()
});

export type ClientUrlPatchZodType = z.infer<typeof zClientUrlPatch>;

export const zDPoPTokenExpirationValidationMode = z.int();

export type DPoPTokenExpirationValidationModeZodType = z.infer<typeof zDPoPTokenExpirationValidationMode>;

export const zIdentityProvider = z.object({
    scheme: z.optional(z.string()),
    displayName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    enabled: z.optional(z.boolean()),
    type: z.optional(z.string()),
    properties: z.optional(z.record(z.string(), z.string()))
});

export type IdentityProviderZodType = z.infer<typeof zIdentityProvider>;

export const zIdentityResource = z.object({
    required: z.optional(z.boolean()),
    emphasize: z.optional(z.boolean()),
    enabled: z.optional(z.boolean()),
    name: z.optional(z.string()),
    displayName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    description: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    showInDiscoveryDocument: z.optional(z.boolean()),
    userClaims: z.optional(z.array(z.string())),
    properties: z.optional(z.record(z.string(), z.string()))
});

export type IdentityResourceZodType = z.infer<typeof zIdentityResource>;

export const zSecret = z.object({
    description: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    value: z.optional(z.string()),
    expiration: z.optional(z.union([
        z.null(),
        z.iso.datetime()
    ])),
    type: z.optional(z.string())
});

export type SecretZodType = z.infer<typeof zSecret>;

export const zApiResource = z.object({
    requireResourceIndicator: z.optional(z.boolean()),
    apiSecrets: z.optional(z.array(zSecret)),
    scopes: z.optional(z.array(z.string())),
    allowedAccessTokenSigningAlgorithms: z.optional(z.array(z.string())),
    enabled: z.optional(z.boolean()),
    name: z.optional(z.string()),
    displayName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    description: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    showInDiscoveryDocument: z.optional(z.boolean()),
    userClaims: z.optional(z.array(z.string())),
    properties: z.optional(z.record(z.string(), z.string()))
});

export type ApiResourceZodType = z.infer<typeof zApiResource>;

export const zTokenExpiration = z.int();

export type TokenExpirationZodType = z.infer<typeof zTokenExpiration>;

export const zTokenUsage = z.int();

export type TokenUsageZodType = z.infer<typeof zTokenUsage>;

export const zClient = z.object({
    enabled: z.optional(z.boolean()),
    clientId: z.optional(z.string()),
    protocolType: z.optional(z.string()),
    clientSecrets: z.optional(z.array(zSecret)),
    requireClientSecret: z.optional(z.boolean()),
    clientName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    description: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    clientUri: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    logoUri: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    requireConsent: z.optional(z.boolean()),
    allowRememberConsent: z.optional(z.boolean()),
    allowedGrantTypes: z.optional(z.array(z.string())),
    requirePkce: z.optional(z.boolean()),
    allowPlainTextPkce: z.optional(z.boolean()),
    requireRequestObject: z.optional(z.boolean()),
    allowAccessTokensViaBrowser: z.optional(z.boolean()),
    requireDPoP: z.optional(z.boolean()),
    dPoPValidationMode: z.optional(zDPoPTokenExpirationValidationMode),
    dPoPClockSkew: z.optional(z.string().regex(/^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$/)),
    redirectUris: z.optional(z.array(z.string())),
    postLogoutRedirectUris: z.optional(z.array(z.string())),
    frontChannelLogoutUri: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    frontChannelLogoutSessionRequired: z.optional(z.boolean()),
    backChannelLogoutUri: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    backChannelLogoutSessionRequired: z.optional(z.boolean()),
    allowOfflineAccess: z.optional(z.boolean()),
    allowedScopes: z.optional(z.array(z.string())),
    alwaysIncludeUserClaimsInIdToken: z.optional(z.boolean()),
    identityTokenLifetime: z.optional(z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])),
    allowedIdentityTokenSigningAlgorithms: z.optional(z.array(z.string())),
    accessTokenLifetime: z.optional(z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])),
    authorizationCodeLifetime: z.optional(z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])),
    absoluteRefreshTokenLifetime: z.optional(z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])),
    slidingRefreshTokenLifetime: z.optional(z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])),
    consentLifetime: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])),
    pushedAuthorizationLifetime: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])),
    requirePushedAuthorization: z.optional(z.boolean()),
    refreshTokenUsage: z.optional(zTokenUsage),
    updateAccessTokenClaimsOnRefresh: z.optional(z.boolean()),
    refreshTokenExpiration: z.optional(zTokenExpiration),
    accessTokenType: z.optional(zAccessTokenType),
    enableLocalLogin: z.optional(z.boolean()),
    identityProviderRestrictions: z.optional(z.array(z.string())),
    includeJwtId: z.optional(z.boolean()),
    claims: z.optional(z.array(zClientClaim)),
    alwaysSendClientClaims: z.optional(z.boolean()),
    clientClaimsPrefix: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    pairWiseSubjectSalt: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    userSsoLifetime: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])),
    userCodeType: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    deviceCodeLifetime: z.optional(z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])),
    cibaLifetime: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])),
    pollingInterval: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])),
    coordinateLifetimeWithUserSession: z.optional(z.union([
        z.null(),
        z.boolean()
    ])),
    allowedCorsOrigins: z.optional(z.array(z.string())),
    initiateLoginUri: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    properties: z.optional(z.record(z.string(), z.string()))
});

export type ClientZodType = z.infer<typeof zClient>;

export const zUserDto = z.object({
    id: z.string(),
    userName: z.string(),
    email: z.string(),
    fullName: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

export type UserDtoZodType = z.infer<typeof zUserDto>;

export const zUserRoles = z.enum(['Admin']);

export type UserRolesZodType = z.infer<typeof zUserRoles>;

export const zGetApiUsersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type GetApiUsersDataZodType = z.infer<typeof zGetApiUsersData>;

/**
 * OK
 */
export const zGetApiUsersResponse = z.array(zUserDto).register(z.globalRegistry, {
    description: 'OK'
});

export type GetApiUsersResponseZodType = z.infer<typeof zGetApiUsersResponse>;

export const zGetApiUsersByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export type GetApiUsersByIdDataZodType = z.infer<typeof zGetApiUsersByIdData>;

/**
 * OK
 */
export const zGetApiUsersByIdResponse = zUserDto;

export type GetApiUsersByIdResponseZodType = z.infer<typeof zGetApiUsersByIdResponse>;

export const zGetApiUsersByIdRolesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export type GetApiUsersByIdRolesDataZodType = z.infer<typeof zGetApiUsersByIdRolesData>;

/**
 * OK
 */
export const zGetApiUsersByIdRolesResponse = z.array(z.string()).register(z.globalRegistry, {
    description: 'OK'
});

export type GetApiUsersByIdRolesResponseZodType = z.infer<typeof zGetApiUsersByIdRolesResponse>;

export const zPutApiUsersByIdRolesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.object({
        role: z.optional(zUserRoles)
    }))
});

export type PutApiUsersByIdRolesDataZodType = z.infer<typeof zPutApiUsersByIdRolesData>;

export const zGetApiIdentityResourcesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type GetApiIdentityResourcesDataZodType = z.infer<typeof zGetApiIdentityResourcesData>;

/**
 * OK
 */
export const zGetApiIdentityResourcesResponse = z.array(zIdentityResource).register(z.globalRegistry, {
    description: 'OK'
});

export type GetApiIdentityResourcesResponseZodType = z.infer<typeof zGetApiIdentityResourcesResponse>;

export const zGetApiIdentityResourcesByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export type GetApiIdentityResourcesByIdDataZodType = z.infer<typeof zGetApiIdentityResourcesByIdData>;

/**
 * OK
 */
export const zGetApiIdentityResourcesByIdResponse = zIdentityResource;

export type GetApiIdentityResourcesByIdResponseZodType = z.infer<typeof zGetApiIdentityResourcesByIdResponse>;

export const zGetApiIdentityProvidersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type GetApiIdentityProvidersDataZodType = z.infer<typeof zGetApiIdentityProvidersData>;

/**
 * OK
 */
export const zGetApiIdentityProvidersResponse = z.array(zIdentityProvider).register(z.globalRegistry, {
    description: 'OK'
});

export type GetApiIdentityProvidersResponseZodType = z.infer<typeof zGetApiIdentityProvidersResponse>;

export const zGetApiClientsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type GetApiClientsDataZodType = z.infer<typeof zGetApiClientsData>;

/**
 * OK
 */
export const zGetApiClientsResponse = z.array(zClient).register(z.globalRegistry, {
    description: 'OK'
});

export type GetApiClientsResponseZodType = z.infer<typeof zGetApiClientsResponse>;

export const zGetApiClientsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export type GetApiClientsByIdDataZodType = z.infer<typeof zGetApiClientsByIdData>;

/**
 * OK
 */
export const zGetApiClientsByIdResponse = zClient;

export type GetApiClientsByIdResponseZodType = z.infer<typeof zGetApiClientsByIdResponse>;

export const zPutApiClientsByIdRedirecturlsData = z.object({
    body: zClientUrlPatch,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export type PutApiClientsByIdRedirecturlsDataZodType = z.infer<typeof zPutApiClientsByIdRedirecturlsData>;

/**
 * OK
 */
export const zPutApiClientsByIdRedirecturlsResponse = zClient;

export type PutApiClientsByIdRedirecturlsResponseZodType = z.infer<typeof zPutApiClientsByIdRedirecturlsResponse>;

export const zGetApiApiResourcesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type GetApiApiResourcesDataZodType = z.infer<typeof zGetApiApiResourcesData>;

/**
 * OK
 */
export const zGetApiApiResourcesResponse = z.array(zApiResource).register(z.globalRegistry, {
    description: 'OK'
});

export type GetApiApiResourcesResponseZodType = z.infer<typeof zGetApiApiResourcesResponse>;

export const zGetApiApiResourcesByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export type GetApiApiResourcesByIdDataZodType = z.infer<typeof zGetApiApiResourcesByIdData>;

/**
 * OK
 */
export const zGetApiApiResourcesByIdResponse = zApiResource;

export type GetApiApiResourcesByIdResponseZodType = z.infer<typeof zGetApiApiResourcesByIdResponse>;
