
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER app
WORKDIR /app
EXPOSE 8080

FROM node:24-slim AS buildnode
ENV NODE_ENV build

WORKDIR /usr/build
COPY UserAdmin/client .
RUN mkdir -p server/wwwroot

WORKDIR /usr/build/client
RUN npm install
RUN npm run build

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY . .
WORKDIR "/src/UserAdmin/server"
RUN dotnet build "./UserAdmin.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./UserAdmin.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY --from=buildnode /usr/build/server/wwwroot wwwroot/
ENTRYPOINT ["dotnet", "UserAdmin.dll"]